name: Cypress Tests

on:
  push:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: npm run build

      - name: Start
        run: npm start

      - name: Run Cypress Tests
        run: pnpm run cypress:test
          