import styles from "./index.module.css";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>FeedAHelp: Server</title>
        <meta name="description" content="Generated by feedahelp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            FeedAHelp <span className={styles.pinkSpan}>DB</span> Server
          </h1>
        </div>
      </main>
    </>
  );
}
